# Generated by Django 3.2.3 on 2022-03-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_product_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.CharField(default=124, max_length=50),
            preserve_default=False,
        ),
    ]
