# Generated by Django 3.2.3 on 2022-03-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account',
        ),
    ]
